### ISSUE TITLE
Suggestion: CSS resets as a separate file

### ISSUE THREAD

**Issue by jinjingngo** [Quantinx/Website-Brief-III#1]
I think ideally below chunk could be put into a separate reset file, 
1. it could be reusable with multiple style sheets
2. and could be cached by the browser.

https://github.com/Quantinx/Website-Brief-III/blob/d6b4fc88fdbdde6255908973913bdab83f622506/style.css#L1-L24

**Comment by Quantinx** [comment]
Will look into implementing
