### ISSUE TITLE
Suggestion: text-decoration

### ISSUE THREAD

**Issue by jinjingngo** [Quantinx/Website-Brief-III#2]
I think we should put this `text-decoration` to what actually it needed, `*` is just too wide(wild) it could ruined something we didn't realized.

https://github.com/Quantinx/Website-Brief-III/blob/d6b4fc88fdbdde6255908973913bdab83f622506/style.css#L7

**Comment by Quantinx** [comment]
Moved to link class, no need for a reset for something which is used once
