### ISSUE TITLE
Suggestion: Investigate the `height` of `<ul>` or maybe the `<li>`

### ISSUE THREAD

**Issue by jinjingngo** [Quantinx/Website-Brief-III#4]
I think we can investigate on the `height` of this `<ul>` or maybe the `<li>`
It's a bit wired, cause in my understanding `<a>` should be contained within `<li>` visually in DOM tree.

<img width="891" alt="image" src="https://github.com/Quantinx/Website-Brief-III/assets/6265893/0a4bd31d-1a84-4d75-b06c-8f35f277fd60">

**Comment by Quantinx** [comment]
Could this be due to both padding and margin being used? element still responds as it should

**Comment by jinjingngo** [comment]
Maybe, but it not looks right to me.
