### ISSUE TITLE
Suggestion: indent consistency

### ISSUE THREAD

**Issue by jinjingngo** [Quantinx/Website-Brief-III#5]
I think this [style.css](https://github.com/Quantinx/Website-Brief-III/blob/main/style.css) file should have a consistent indention style which could made it more readable.

**Comment by Quantinx** [comment]
Could you provide an example of such an inconsistency?

**Comment by jinjingngo** [comment]
Like I underlined the space. I don't think they're necessary.

<img width="878" alt="image" src="https://github.com/Quantinx/Website-Brief-III/assets/6265893/d65085b8-7605-430a-8038-f3deaa6a1768">

And some of them are two whitespaces, but some of them are four whitespaces
<img width="759" alt="image" src="https://github.com/Quantinx/Website-Brief-III/assets/6265893/647afdfb-21e9-44b8-979d-bfec85d0ef7d">

**Comment by jinjingngo** [comment]
The right side is after I made a format. 
<img width="1553" alt="image" src="https://github.com/Quantinx/Website-Brief-III/assets/6265893/9adc2386-59a3-4d33-a450-75b16df061d0">

**Comment by Quantinx** [comment]
reran formatter, looks much better now
